# Generated by Django 3.0.6 on 2021-10-21 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория наград')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Ф.И.О.')),
                ('num', models.IntegerField(verbose_name='Номер приказа')),
                ('name', models.CharField(max_length=400, unique=True, verbose_name='Название приказа')),
                ('year', models.IntegerField(null=True, verbose_name='Год издания')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, upload_to='docs', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название медали')),
                ('image', models.FileField(upload_to='medals')),
                ('established', models.CharField(max_length=100, verbose_name='Учрежден')),
                ('rules', models.TextField(verbose_name='Правила награждения')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('I', models.CharField(max_length=50, verbose_name='Имя')),
                ('O', models.CharField(max_length=50, verbose_name='Отчество')),
                ('number', models.CharField(max_length=20, verbose_name='Личный номер военнослужащего')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=2)),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=200, verbose_name='Место рождения')),
                ('place_of_reg', models.CharField(max_length=200, verbose_name='Место регистрации')),
                ('date_of_start', models.DateField(verbose_name='Дата начала прохождения службы')),
                ('biography', models.TextField(blank=True, default='', verbose_name='Краткие биографические сведения')),
                ('medals', models.ManyToManyField(blank=True, to='medals.Medal', verbose_name='Награды')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.Rank', verbose_name='Звание')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.Status', verbose_name='Должность')),
            ],
        ),
    ]
