# Generated by Django 3.0.6 on 2021-10-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория наград', 'verbose_name_plural': 'Категории наград'},
        ),
        migrations.AlterModelOptions(
            name='soldier',
            options={'ordering': ['F'], 'verbose_name': 'Офицер', 'verbose_name_plural': 'Офицеры'},
        ),
        migrations.RemoveField(
            model_name='documents',
            name='year',
        ),
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата издания'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='author',
            field=models.CharField(max_length=150, verbose_name='Автор приказа'),
        ),
    ]
