# Generated by Django 3.0.6 on 2021-10-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medals', '0002_auto_20211021_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='established',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medals.Documents', verbose_name='Учрежден'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='image',
            field=models.FileField(upload_to='medals', verbose_name='Изображение'),
        ),
    ]
